---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: zap-dc
  creationTimestamp:
parameters: 
  - name: CPU_REQUEST
    displayName: Requested CPU
    description: Requested CPU
    required: true
    value: '50m'
  - name: CPU_LIMIT
    displayName: CPU upper limit
    description: CPU upper limit
    required: true
    value: '1000m'
  - name: MEMORY_REQUEST
    displayName: Requested memory
    description: Requested memory
    required: true
    value: '150M'
  - name: MEMORY_LIMIT
    displayName: Memory upper limit
    description: Memory upper limit
    required: true
    value: '1500M'      
objects:
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: zap
      creationTimestamp:
      annotations:
        description: Defines how to deploy the container.
    spec:
      strategy:
        type: Recreate
        recreateParams:
          timeoutSeconds: 1100
        resources: {}
        activeDeadlineSeconds: 1200
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - zap
            from:
              kind: ImageStreamTag
              namespace: tbiwaq-tools
              name: zap:latest
            lastTriggeredImage:
        - type: ConfigChange
      replicas: 1
      test: false
      selector:
        name: zap
      template:
        metadata:
          name: zap
          creationTimestamp:
          labels:
            name: zap
        spec:
          containers:
            - name: zap
              image:
              ports:
              env: {}
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              terminationMessagePath: "/dev/termination-log"
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
    status:
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      updatedReplicas: 0
      availableReplicas: 0
      unavailableReplicas: 0
